apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amaczar
  description: Stores ECS metadata
  tags:
    - amaczar
    - sandbox
    - amczar-tf
    - surbhi
    - distribute
    - terraform
  annotations:
    Environment: sandbox
    CreatedBy: terraform
    Name: amaczar
    Repository: amaczar-tf
    Owner: surbhi
    Team: distribute
spec:
  type: Service
  owner: Surbhi
  team: SRE
  system: ECS service
  lifecycle: Experimental
