apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amaczar
  description: Stores ECS metadata
  tags:
    - ecs
    - sandbox
  annotations:
    Environment: sandbox
    CreatedBy: terraform
    Name: app
    Repository: app-tf
    Owner: vijay
    Team: sre
spec:
  type: Service
  owner: Surbhi
  team: SRE
  system: ECS service
  lifecycle: Experimental
