apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ecs-metadata
  description: Stores ECS metadata
  tags:
    - pattern
    - ecs
    - sandbox
    - terraform
    - pattern-tf
  annotations:
    Environment: sandbox
    CreatedBy: terraform
    Name: pattern
    Repository: pattern-tf
spec:
  type: Service
  owner: Amit k Tiwari
  team: SRE
  system: ECS
  lifecycle: Experimental
